### ISSUE TITLE
Traceback of line 217, 197, 150 in GoBooDo.py, line 15 in makePDF.py and IndexError

### ISSUE THREAD

**Issue by craziecaesium** [vaibhavk97/GoBooDo#62]
Hi, I had this "Could not fetch link for page PAXXX" for some pages using default `settings.json`, and showed:

```
(2, 'Usage: pytesseract [-l lang] input_file')
(2, 'Usage: pytesseract [-l lang] input_file')
(2, 'Usage: pytesseract [-l lang] input_file')
(2, 'Usage: pytesseract [-l lang] input_file')
(2, 'Usage: pytesseract [-l lang] input_file')
------------------- Creating PDF -------------------
Traceback (most recent call last):
  File "GoBooDo.py", line 217, in <module>
    book.start()
  File "GoBooDo.py", line 197, in start
    self.processBook()
  File "GoBooDo.py", line 150, in processBook
    service.makePdf()
  File "C:\Users\user\Desktop\GoBooDo-master\makePDF.py", line 15, in makePdf
    firstPath = self.imageNameList[0]
IndexError: list index out of range
```

So I assume pdf cannot be created due to the unavailability of some pages. ​I tried changing `settings.json` and use the `proxies.txt` given: 

```
"country": "com",
   ​"page_resolution": 500,
   ​"tesseract_path": "C:\\program Files\\Tesseract-OCR\\tesseract.exe",
   ​"proxy_links": 1,
   ​"proxy_images": 1,
   ​"max_retry_links": 4,
   ​"max_retry_images": 4,
   ​"global_retry_time": 30
```

and it showed 

```
Using proxy 203.190.53.45:53927 for the url of page PA131
Could not connect with this proxy
Using proxy 85.90.215.111:3128 for the url of page PA131
Could not connect with this proxy
Using proxy 85.90.215.111:3128 for the url of page PA131
Could not connect with this proxy
Using proxy 1.10.189.156:34899 for the url of page PA131
Could not connect with this proxy
Using proxy 115.124.86.107:37600 for the url of page PA131
Could not connect with this proxy
Could not fetch link for page PA131
```

and the same IndexError occurred. the folder `data` has `obstinatePages.pkl`, `pageLinkDict.pkl`, `pagesFetched.pkl` and the folder `Images` is empty.

Can someone please tell me what's wrong? I am not good with stuff like these, so I don't know where to find other proxies or how to configure `pytesseract`. I also tried downloading the books mentioned in the issues elsewhere that are working, but those books did not work for me as well.

**Comment by craziecaesium** [comment]
After few days of downloading the same book consecutively, the "could not fetch link" is solved, I'm assuming they rotate the pages that can be previewed everyday regardless of the domain we use (`country` in `settings.json`).

But the same thing occurs when creating PDF, i.e. line 217, 197, 150 in `GoBooDo.py`, line 15 in `makePDF.py` and IndexError.

**Comment by minamotorin** [comment]
@craziecaesium 

Hi, `IndexError` is same as #53. Looking at [here](https://github.com/madmaze/pytesseract/issues/285), the cause is that pytesseract mistakes for tesseract-ocr and pytesseract.

First, you should do the same as solution of #53. If error still occures, replace [63 to 67 lines of storeImages.py](https://github.com/vaibhavk97/GoBooDo/blob/master/storeImages.py#L63,L67) with the following (be careful with indention):

```python3
        pytesseract.pytesseract.tesseract_cmd = self.tesserPath
        text = pytesseract.image_to_string(bw)
```

**Comment by craziecaesium** [comment]
Hi,

So I installed tesseract orc from UB Mannheim and set the PATH, and the IndexError issue was solved! thank you so much! now the only thing is there are a lot of "Image not available" pages.
